on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

name: on-commit-to-main

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send pull-request
        run: |
          PROJECT_NAME = ${{vars.PROJECT_NAME}}
          USER_NAME = ${{vars.USER_NAME }}
          USER_EMAIL = ${{vars.USER_EMAIL }}
          ACCESS_TOKEN = ${{ secrets.ACCESS_TOKEN }}
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          REPOSITORY="PrashantMohta/modlinks"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="update-$PROJECT_NAME-to-$LATEST_TAG"

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          git clone \
            --depth=1 \
            --branch=main \
            https://$USER_NAME:$ACCESS_TOKEN@github.com/$REPOSITORY \
            $FOLDER

          cd $FOLDER

          # Setup the committers identity.
          git config user.email "$USER_EMAIL"
          git config user.name "$USER_NAME"

          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          # Update the script files to the latest version.
          echo "$now" > ModLinks.xml

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "update $PROJECT_NAME to $LATEST_TAG"
          git push origin $BRANCH_NAME

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < ACCESS_TOKEN
          gh pr create \
            --body "" \
            --title "Update $PROJECT_NAME to $LATEST_TAG" \
            --head "$BRANCH_NAME" \
            --base "main"
